version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/llm_intent/"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
